replicaCount: 1

image:
  repository: registry.gdutnic.com/gdutdays/gdutdays
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# 16位字符串私钥
gdutdays:
  secret: "changemechangeme"

service:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31880
    - name: metrics
      port: 8092
      targetPort: 8092

ingress:
  enabled: false
  className: "nginx"  # 根据您的 Ingress Controller 的 class 名称
  annotations:
    nginx.ingress.kubernetes.io/server-tokens: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /gdutDay3/$1
  hosts:
    - host: gdutdays.gdutelc.com
      paths:
        - path: /v3/(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: gdutdays-tls
      hosts:
        - gdutdays.gdutelc.com

# ServiceMonitor 配置
serviceMonitor:
  enabled: true
  # namespace: monitoring  # 根据您的实际情况
  interval: 30s
  scrapeTimeout: 10s
  path: /actuator/prometheus  # 添加此行，指定监控路径
  labels: {}
  annotations: {}
  metricRelabelings: []
  relabelings: []
  honorLabels: false
  selector:
    matchLabels:
      app.kubernetes.io/name: gdutday4

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}