apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gdutdays4.fullname" . }}
  labels:
    {{- include "gdutdays4.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gdutdays4.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gdutdays4.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.gdutdays.secret }}
            - name: GDUTDAY_SECRET
              value: "{{ .Values.gdutdays.secret }}"
            {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}