{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gdutdays4.fullname" . }}
  labels:
    {{- include "gdutdays4.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "gdutdays4.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      {{- if .Values.serviceMonitor.path }}
      path: {{ .Values.serviceMonitor.path | quote }}
      {{- end }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
{{- end }}