apiVersion: v1
kind: Service
metadata:
  name: {{ include "gdutdays4.fullname" . }}
  labels:
    {{- include "gdutdays4.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if and (eq $.Values.service.type "NodePort") (defined .nodePort) }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "gdutdays4.selectorLabels" . | nindent 4 }}